# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f5dff662990735e8836afb8e7e16fc8ed5a46a02a19149bb92896d1524adaa7b058e98820e24618a4b8d39c7de48506499cbdc6ce8e524fb9d019d85f12cb9ee

test:
  secret_key_base: f5a816f597ed32e8180a8238d7ed19d6f6fbb7037532f4cc2393997557ac75580a9bdfe689ea6445cdd2e7287ad2cf857a664cc8ee2ae0a191e9ca46393a689c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
